---
jobs:
  test:
    name: molecule test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up private key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install required dependencies
        run: pip install -r requirements.txt
      - run: molecule test --all
name: Molecule Test
"on":
  - push
  - pull_request
