---
jobs:
  test:
    name: molecule test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up private key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install required dependencies
        run: pip install -r requirements.txt
      - name: Log into RedHat
        uses: azure/docker-login@v1
        with:
          login-server: registry.redhat.io
          username: ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME }}
          password: ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD }}
      - name: Enable execution of different multi-architecture containers
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: molecule test --all
        env:
          REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME: ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME }}
          REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD: ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD }}
name: Molecule Test
"on":
  - push
  - pull_request
